### ISSUE TITLE
render apiproxy is erroring with a PostClientFlow

### ISSUE THREAD

**Issue by carlosmscabral** [apigee/apigee-go-gen#10]
Using the following command:

apigee-go-gen render apiproxy   --template ./template/apiproxy.yaml \
--set-oas spec=./productOrdering-v2.yaml \
--include ./template/*.tmpl \
--output ./out/apiproxies/productOrdering-v2

I receive the following error message: 

Error: unknown node "PostClientFlow" found at "Root.ProxyEndpoints.0.ProxyEndpoint(name: default)"

It seems that PostClientFlows are not well understood by the tool.

The full template is below:

APIProxy:
  .revision: 1
  .name: teste
  DisplayName: {{$.Values.spec.info.title}}
  Description: {{$.Values.spec.info.description}}
  # BasePaths: /api/geographicAddressManagement/v1
  Policies:
    - Policy: RF-unknown-operation
    - Policy: FC-ErrorHandling
    - Policy: OAuthV2-VerifyAccessToken
    - Policy: Q-EnforceProductQuota
    - Policy: AM-SetDynamicHost
    - Policy: AM-SetCurrentFlow
    - Policy: FC-SetLoggingVar
    - Policy: ML-CloudLogging
  ProxyEndpoints:
    ProxyEndpoint: default
  Resources:
    - Resource: oas://spec.yaml
    - Resource: properties://config.properties
    - Resource: jsc://transformPath.js
  TargetEndpoints:
    TargetEndpoint: default
Policies:
  $ref: ./policies.yaml#/
ProxyEndpoints:
  - ProxyEndpoint:
      .name: default
      FaultRules:
        FaultRule:
          .name: SF Error Handling
          Step:
            Name: FC-ErrorHandling
      PreFlow:
        Request:
          - Step:
              Name: OAuthV2-VerifyAccessToken
          - Step:
              Name: Q-EnforceProductQuota
          - Step:
              Name: FC-SetLoggingVar
        Response: {}
      Flows:
        #{{- range $path, $pathItem := $.Values.spec.paths }}
        #{{- range $verb, $opItem := $pathItem }}
        #{{- if eq (include "get_visibility" $opItem) "INTERNAL" }}
        #{{- fmt_printf "Skipping internal operation '%s' (%s %s)\n" $opItem.operationId $verb $path }}
        #{{-  continue }}
        #{{-  end  }}
        - Flow:
            .name: {{$opItem.operationId}}
            Condition: (proxy.pathsuffix MatchesPath "{{  regexReplaceAll "{[^}]*}" $path "*" }}") and (request.verb = "{{ $verb | upper }}")
        #{{- end }}
        #{{- end }}
        - Flow:
            .name: unsupported_operation
            Description: Unsupported operation
            Request:
              Step:
                Name: RF-unknown-operation
      PostFlow:
        Response:
          Step:
            Name: FC-SetLoggingVar
      PostClientFlow:
        Response:
          Step:
            Name: ML-CloudLogging
      HTTPProxyConnection:
        BasePath: /v1
    
      RouteRule:
        .name: default
        TargetEndpoint: default
TargetEndpoints:
  - TargetEndpoint:
      .name: default
      FaultRules:
        FaultRule:
          .name: SF Error Handling
          Step:
            Name: FC-ErrorHandling
      HTTPTargetConnection:
        SSLInfo:
          Enabled: true
          Enforce: true
          IgnoreValidationErrors: true
        URL: '{customTarget}{customSuffix}'
      PreFlow:
        Request:
          Step:
            Name: AM-SetDynamicHost
      PostFlow:
        Request:
          Step:
            Name: FC-SetLoggingVar
        Response:
          Step:
            Name: FC-SetLoggingVar
Resources:
  - Resource:
      Type: oas
      #{{ os_writefile "./spec.yaml" $.Values.spec_string }}
      #{{ remove_oas_extensions "./spec.yaml" }}
      Path: ./spec.yaml
  - Resource:
      Type: properties
      #{{ os_copyfile "./config.properties" "./resources/config.properties" }}
      Path: ./config.properties

**Comment by micovery** [comment]
Fixed by https://github.com/apigee/apigee-go-gen/pull/15
