### ISSUE TITLE
Cloud Shell Linux - mktemp: too few X's in template ‘apigee-go-gen-tmp’

### ISSUE THREAD

**Issue by blackrookgeek** [apigee/apigee-go-gen#11]
Install script: https://github.com/apigee/apigee-go-gen/blob/main/install
Line 132:
createTmpDir() {
   ret_val=$(mktemp -dt ${BINARY_FILENAME}-tmp)
}

results in:
mktemp: too few X's in template ‘apigee-go-gen-tmp’

suggest changing to:
   ret_val=$(mktemp -dt ${BINARY_FILENAME}-XXX)

as mktemp requires at least three "X"s to be included in the name.

**Comment by micovery** [comment]
Fixed by https://github.com/apigee/apigee-go-gen/pull/13
